# Generated by Django 6.0.6 on 2026-07-06 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeprofile_date_of_birth_resumeprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='resumeprofile',
            name='website',
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='resumeprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ResumeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'Resume Summary',
                'verbose_name_plural': 'Resume Summaries',
            },
        ),
    ]
