# Generated by Django 6.0.6 on 2026-07-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resumeprofile_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
