# Generated by Django 6.0.6 on 2026-08-23 06:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPrepPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(max_length=150)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=50)),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('job_description', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('overall_readiness_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_prep_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Prep Plan',
                'verbose_name_plural': 'Interview Prep Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewReadiness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technical_score', models.IntegerField(default=0)),
                ('behavioral_score', models.IntegerField(default=0)),
                ('project_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('weak_areas', models.JSONField(blank=True, default=list)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to='interview_prep.interviewprepplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockInterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='AI Mock Interview', max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('hr', 'HR & Culture'), ('system_design', 'System Design'), ('coding', 'Coding & Algorithms'), ('domain_knowledge', 'Domain Knowledge'), ('case_study', 'Case Study'), ('communication', 'Communication'), ('role_specific', 'Role Specific'), ('managerial', 'Managerial')], default='technical', max_length=50)),
                ('total_questions', models.IntegerField(default=5)),
                ('current_question_index', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=30)),
                ('overall_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_sessions', to='interview_prep.interviewprepplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MockInterviewTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.IntegerField(default=0)),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('hr', 'HR & Culture'), ('system_design', 'System Design'), ('coding', 'Coding & Algorithms'), ('domain_knowledge', 'Domain Knowledge'), ('case_study', 'Case Study'), ('communication', 'Communication'), ('role_specific', 'Role Specific'), ('managerial', 'Managerial')], default='technical', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=30)),
                ('user_answer', models.TextField(blank=True, default='')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evaluation', models.TextField(blank=True, default='')),
                ('follow_up_hint', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='interview_prep.mockinterviewsession')),
            ],
            options={
                'ordering': ['turn_index'],
            },
        ),
        migrations.CreateModel(
            name='PrepTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('hr', 'HR & Culture'), ('system_design', 'System Design'), ('coding', 'Coding & Algorithms'), ('domain_knowledge', 'Domain Knowledge'), ('case_study', 'Case Study'), ('communication', 'Communication'), ('role_specific', 'Role Specific'), ('managerial', 'Managerial')], default='technical', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=30)),
                ('priority', models.IntegerField(default=1)),
                ('proficiency_status', models.CharField(choices=[('strong', 'Strong'), ('weak', 'Weak'), ('missing', 'Missing'), ('priority', 'Priority Study Area')], default='weak', max_length=30)),
                ('what_to_study', models.JSONField(blank=True, default=list)),
                ('what_to_practice', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='interview_prep.interviewprepplan')),
            ],
            options={
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PrepResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('provider', models.CharField(blank=True, default='', max_length=150)),
                ('resource_type', models.CharField(choices=[('documentation', 'Official Documentation'), ('course', 'Course'), ('tutorial', 'Tutorial'), ('article', 'Article'), ('video', 'Video'), ('practice_platform', 'Practice Platform'), ('book', 'Book')], default='documentation', max_length=50)),
                ('is_free', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='interview_prep.preptopic')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('hr', 'HR & Culture'), ('system_design', 'System Design'), ('coding', 'Coding & Algorithms'), ('domain_knowledge', 'Domain Knowledge'), ('case_study', 'Case Study'), ('communication', 'Communication'), ('role_specific', 'Role Specific'), ('managerial', 'Managerial')], default='technical', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=30)),
                ('source_type', models.CharField(choices=[('conceptual', 'Conceptual'), ('technical', 'Technical'), ('resume_based', 'Resume Based'), ('project_based', 'Project Based'), ('jd_specific', 'Job Description Specific'), ('behavioral', 'Behavioral'), ('scenario', 'Scenario Based')], default='technical', max_length=50)),
                ('ideal_answer_outline', models.TextField(blank=True, default='')),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_prep.interviewprepplan')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='interview_prep.preptopic')),
            ],
            options={
                'ordering': ['category', 'difficulty', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_answer', models.TextField()),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_correct', models.BooleanField(default=False)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('missing_points', models.JSONField(blank=True, default=list)),
                ('ideal_answer', models.TextField(blank=True, default='')),
                ('improvement_tips', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='interview_prep.interviewquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
