# Generated by Django 6.0.6 on 2026-06-17 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL),
        ),
    ]
