# Generated by Django 6.0.6 on 2026-08-23 05:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(db_index=True, default='Software Engineering', max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('estimated_duration_weeks', models.PositiveIntegerField(default=16)),
                ('icon_name', models.CharField(blank=True, default='code', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career Role',
                'verbose_name_plural': 'Career Roles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('total_phases', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='roadmaps.careerrole')),
            ],
            options={
                'verbose_name': 'Roadmap Template',
                'verbose_name_plural': 'Roadmap Templates',
                'ordering': ['career_role__title'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_hours', models.PositiveIntegerField(default=20)),
                ('learning_objective', models.TextField(blank=True, default='')),
                ('prerequisites_summary', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='roadmaps.roadmap')),
            ],
            options={
                'verbose_name': 'Roadmap Phase',
                'verbose_name_plural': 'Roadmap Phases',
                'ordering': ['order'],
                'unique_together': {('roadmap', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('learning_objective', models.TextField()),
                ('what_to_learn', models.JSONField(blank=True, default=list)),
                ('what_to_practice', models.JSONField(blank=True, default=list)),
                ('what_to_build', models.JSONField(blank=True, default=list)),
                ('completion_criteria', models.TextField()),
                ('estimated_hours', models.PositiveIntegerField(default=5)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='roadmaps.roadmapphase')),
                ('prerequisite_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_steps', to='roadmaps.roadmapstep')),
            ],
            options={
                'verbose_name': 'Roadmap Step',
                'verbose_name_plural': 'Roadmap Steps',
                'ordering': ['order'],
                'unique_together': {('phase', 'order')},
            },
        ),
        migrations.CreateModel(
            name='RoadmapResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('resource_type', models.CharField(choices=[('documentation', 'Documentation'), ('article', 'Article'), ('video', 'Video'), ('course', 'Course'), ('book', 'Book'), ('practice', 'Practice Platform')], default='documentation', max_length=30)),
                ('provider', models.CharField(blank=True, default='', max_length=100)),
                ('is_free', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='roadmaps.roadmapstep')),
            ],
            options={
                'verbose_name': 'Roadmap Resource',
                'verbose_name_plural': 'Roadmap Resources',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserRoadmapProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='roadmaps.careerrole')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_users', to='roadmaps.roadmapstep')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='roadmaps.roadmap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Roadmap Progress',
                'verbose_name_plural': 'User Roadmap Progresses',
                'ordering': ['-last_activity_at'],
                'unique_together': {('user', 'career_role')},
            },
        ),
        migrations.CreateModel(
            name='UserStepProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_step_progresses', to='roadmaps.roadmapstep')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progresses', to='roadmaps.userroadmapprogress')),
            ],
            options={
                'verbose_name': 'User Step Progress',
                'verbose_name_plural': 'User Step Progresses',
                'ordering': ['step__phase__order', 'step__order'],
                'unique_together': {('user_progress', 'step')},
            },
        ),
    ]
