# Generated by Django 6.0.6 on 2026-08-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroadmapprogress',
            name='skill_gap_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
